Revert "Update eslint-config-wikimedia"
Doesn’t work in CI:

> /builds/repos/m3api/m3api/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.cjs:768
> const lastLineBreakPos = text.slice(0, jsdocNode.range[0]).search(/\n[\t]*$/v);
>                                                                   ^
> SyntaxError: Invalid regular expression flags

We really need to get off our old supported Node version, not because of
anything in our own code, but purely because everyone else keeps
dropping support for Node versions left and right.

This reverts commit c83761aa954047f195e1ee7c5e2b480e606a9b5b.